--  VES Collector
--  Virtual Event Streaming (VES) Collector is RESTful collector for processing JSON messages. The collector verifies the source and validates the events against VES schema before distributing to DMAAP MR topics 
--
--  The version of the OpenAPI document: 1.4.5
--  
--
--  NOTE: This package is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Streams;
with Ada.Containers.Vectors;
package Ves.Models is


   --  ------------------------------
   --  View
   --  ------------------------------
   type View_Type is
     record
       Content_Type : Swagger.Nullable_UString;
     end record;

   package View_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => View_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in View_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in View_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out View_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out View_Type_Vectors.Vector);



   --  ------------------------------
   --  ModelAndView
   --  ------------------------------
   type ModelAndView_Type is
     record
       Empty : Swagger.Nullable_Boolean;
       Model : Swagger.Object;
       Reference : Swagger.Nullable_Boolean;
       Status : Swagger.UString;
       View : Ves.Models.View_Type;
       View_Name : Swagger.UString;
       Title : Swagger.UString;
     end record;

   package ModelAndView_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ModelAndView_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ModelAndView_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ModelAndView_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ModelAndView_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ModelAndView_Type_Vectors.Vector);



end Ves.Models;
