--  VES Collector
--  Virtual Event Streaming (VES) Collector is RESTful collector for processing JSON messages. The collector verifies the source and validates the events against VES schema before distributing to DMAAP MR topics 
--
--  The version of the OpenAPI document: 1.4.5
--  
--
--  NOTE: This package is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Ves.Models;
with Swagger.Clients;
package Ves.Clients is

   type Client_Type is new Swagger.Clients.Client_Type with null record;

   --  errorHtml
   procedure Error_Html_Using_DELETE
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_GET
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_HEAD
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_OPTIONS
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_PATCH
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_POST
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  errorHtml
   procedure Error_Html_Using_PUT
      (Client : in out Client_Type;
       Result : out Ves.Models.ModelAndView_Type);

   --  mainPage
   procedure Main_Page_Using_GET
      (Client : in out Client_Type;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST1
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST10
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST11
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST2
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST3
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST4
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST5
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST6
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST7
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST8
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --  receiveEvent
   procedure Receive_Event_Using_POST9
      (Client : in out Client_Type;
       Json_Payload : in Swagger.UString;
       Result : out Swagger.UString);

   --   procedure Update_Todo
      --   (Client : in out Client_Type;
       --   View_Name : in Swagger.UString;
       --   Title : in Swagger.UString;
       --   Status : in Swagger.UString;
       --   Result : out Ves.Models.ModelAndView_Type);
end Ves.Clients;
